dataset:
  name: 3D_FUTURE #3D_FUTURE ModelNet
  category: chair #chair lamp cabinet sofa table all
  n_points: 2048
  split: train

model:
  name: SeedFormer
  #upsample_factors: [1,4,4]
  feat_dim: 512
  embed_dim: 128
  num_p0: 512
  n_knn: 20
  radius: 1
  up_factors: [1,2,2]
  seed_factor: 2
  interpolate: 'three'
  attn_channel: True


optimizer: {
    type: Adam,
    kwargs: {
      lr: 0.00008,  #0.001
      weight_decay: 0, 
      betas: [.9, .999]
    }}
scheduler: {
  type: StepLR,
  kwargs_1: {
    decay_step: 50, 
    milestones: [50, 100, 150, 200, 250],
    gamma: 0.98, #
  },
  type: GradualWarmup,
  kwargs_2: {
    total_epoch: 20,
    #warmup_epochs: 20,
  }

  }

train :
  seed: 1
  device: [2]
  batch_size: 16 #24 #48
  num_workers: 8
  epochs: 400
  save_freq: 25
  out_path: ./outpath_seed_3dfuture
  resume: False
  #coarse_num: 256
  
  source_model_path: ./pretrained_source/seedformer-061.pth
  

test :
  split: test
  batch_size: 1
  num_workers: 1
  gpu: [0]
  loss_func: cd_l2
  #odel_path: ./pretrained_source/seedformer-061.pth
  #model_path: ./pretrained_source/ckpt-best-048.pth
 
