dataset:
  name: 3D_FUTURE #3D_FUTURE ModelNet
  category: chair #chair lamp cabinet sofa table all
  n_points: 2048
  split: train

model:
  name: SnowflakeNet
  dim_feat: 512 #512
  up_factors: [ 2, 2]
  num_pc: 256
  num_p0: 512
  bounding: True
  radius: 1.0

optimizer: {
    type: Adam,
    kwargs: {
      lr: 0.00008, # 0.00008
      weight_decay: 0,
      betas: [.9, .999]
    }}
scheduler: {
  type: StepLR,
  kwargs: {
    decay_step: 50, #50
    gamma: 0.5, #0.5
  }}

train :
  seed: 1
  device: [2]
  batch_size: 12   #32
  num_workers: 4
  epochs: 300
  save_freq: 200
  out_path: ./outpath_snow
  resume: False
  coarse_num: 256
  source_model_path: ./pretrained_source/snow__crn.pth



test :
  split: test
  batch_size: 1 
  num_workers: 1
  gpu: [0]
  loss_func: cd_l2
#  source_model_path: ./outpath_snow/sofa/checkpoints/ckpt-best-source.pth
  #model_path: ./outpath_snow/sofa/checkpoints/ckpt-best.pth
