dataset:
  name: 3D_FUTURE #3D_FUTURE ModelNet
  category: chair #chair lamp cabinet sofa table all
  n_points: 2048
  split: train


model:
  name: SnowflakeNet
  dim_feat: 512
  up_factors: [ 2, 2]
  num_pc: 256
  num_p0: 512
  bounding: True
  radius: 1.0

optimizer: {
    type: Adam,
    kwargs: {
      lr: 0.00008,
      weight_decay: 0,
      betas: [.9, .999]
    }}
scheduler: {
  type: StepLR,
  kwargs: {
    decay_step: 50,
    gamma: 0.5,
  }}

train :
  K: 4 
  seed: 1
  device: [0,1]
  batch_size: 30 #32
  num_workers: 8 #
  epochs: 500
  save_freq: 600
  out_path: ./outpath_snow_k3
  resume: False
  coarse_num: 256
  #source_model_path: ./pretrained_source/snow_crn.pth
  source_model_path: ./pretrained_source/ckpt-best-048.pth
  #model_path: /data1/xp/experiments/completion/pretrained/ckpt-best-c3d-rec.pth


test :
  split: test
  batch_size: 1
  num_workers: 1
  #gpu: [0]
  loss_func: cd_l2
  #model_path: /data1/xp/experiments/completion/pretrained/ckpt-best-c3d-rec.pth
