dataset:
  name: ModelNet #3D_FUTURE ModelNet
  category: all #chair lamp cabinet sofa table all
  n_points: 2048
  split: train

optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0001, #0.0001
  weight_decay : 0.0005
}}

scheduler: {
  type: LambdaLR,
  kwargs: {
  decay_step: 21,
  lr_decay: 0.9,
  lowest_decay: 0.02  # min lr = lowest_decay * lr
}}

bnmscheduler: {
  type: Lambda,
  kwargs: {
  decay_step: 21,
  bn_decay: 0.5,
  bn_momentum: 0.9,
  lowest_decay: 0.01
}}


model : {
    name: AdaPoinTr, 
    num_query: 256,
    num_points: 2048,
    center_num: [512, 256],
    global_feature_dim: 512,
    encoder_type: graph,
    decoder_type: fc,
    encoder_config: {
      embed_dim: 384,
      depth: 6,
      num_heads: 6,
      k: 8,
      n_group: 2,
      mlp_ratio: 2.,
      block_style_list: ['attn-graph', 'attn', 'attn', 'attn', 'attn', 'attn'], 
      combine_style: 'concat',
    },
    decoder_config: {
      embed_dim: 384,
      depth: 8,
      num_heads: 6,
      k: 8,
      n_group: 2,
      mlp_ratio: 2.,
      self_attn_block_style_list: ['attn-graph', 'attn', 'attn', 'attn', 'attn', 'attn', 'attn', 'attn'], 
      self_attn_combine_style: 'concat',
      cross_attn_block_style_list: ['attn-graph', 'attn', 'attn', 'attn', 'attn', 'attn', 'attn', 'attn'], 
      cross_attn_combine_style: 'concat',
    }
}

#total_bs : 48 #48
#step_per_update : 1
#max_epoch : 600

consider_metric: CDL2
train :
  seed: 1
  gpu: [0]
  batch_size: 64 #48
  num_workers: 8
  epochs: 600
  save_freq: 300
  out_path: ./outpath_adapointr
  resume: False
  step_per_update : 1
  #model_path: ./pretrained_source/snow_crn.pth


test :
  split: test
  batch_size: 1
  num_workers: 1
  gpu: [0]
  loss_func: cd_l2
  #model_path: ../pretrained_source/adapointr_crn.pth


  #model_path: /data1/xp/experiments/completion/pretrained/ckpt-best-c3d-rec.pth