dataset:
  name: 3D_FUTURE
  category: all
  n_points: 2048
  split: train

model : {
  name: PCN, num_pred: 2048, encoder_channel: 1024}
  # dim_feat: 512 #512
  # up_factors: [2, 2] #[1, 2, 2]
  # num_pc: 256
  # num_p0: 512
  # bounding: True
  # radius: 1.0

optimizer: {
    type: Adam,
    kwargs: {
      lr: 0.001, # 0.001
      weight_decay: 0,
      betas: [.9, .999]
    }}
scheduler: {
  type: StepLR,
  kwargs: {
    decay_step: 50,
    gamma: 0.5, #0.5
  }}

train :
  seed: 1
  gpu: [0]
  batch_size: 32
  num_workers: 8
  epochs: 500
  save_freq: 500
  out_path: ./outpath
  resume: False
  coarse_num: 256
  #source_model_path: ./pretrained_source/snow_crn.pth
  #model_path: /data1/xp/experiments/completion/pretrained/ckpt-best-c3d-rec.pth


test :
  split: test
  batch_size: 1
  num_workers: 1
  gpu: [0]
  loss_func: cd_l2
  #model_path: ../pretrained_source/pcn_crn.pth
  #model_path: /data1/xp/experiments/completion/pretrained/ckpt-best-c3d-rec.pth
